services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    # command: ["sh", "-c", "npm run prisma && npm run seed && npm start"]
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      DATABASE_URL: "postgresql://test:test@postgres:5432/test"
      JWT_SECRET: "1234"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      postgres:
        condition: service_healthy
    
  postgres:
    image: postgres:13
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      backend:
        condition: service_healthy

  backend_test:
    build:
      context: ./postman
      dockerfile: Dockerfile
    volumes:
      - ./postman-test-report:/etc/newman/newman

  frontend_test:
    build: ./playwright
    volumes:
      - ./frontend-test-report:/app/report
