services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: ["sh", "-c", "yarn prisma migrate deploy && yarn seed && yarn start"]
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://test:test@postgres:5432/test"
    depends_on:
      postgres:
        condition: service_healthy
    
  postgres:
    image: postgres:13
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
